### ISSUE TITLE
Automatically uploads new images to cloud and deletes on local system

### ISSUE THREAD

**Issue by SamuelMereau** [doggo-ninja/bone#16]
While the bone app is open (having the bone icon on the menu bar), the app will watch for when a new image file appears anywhere in the system or moves between a directory. This will then automatically upload the file to the cloud and permanently delete the file on the local system.

To recreate the issue, I did the following:
- Open the bone application and log in
- Drag an image onto the Desktop from something like Google Images, or move a pre-existing image to another directory.
- Open a web browser and view the doggo.ninja dashboard to view the uploaded image

**Comment by SamuelMereau** [comment]
Ok so I am aware that this is an intended feature but it doesn't feel like one

**Comment by kognise** [comment]
As expected, this is a feature and not a bug. If you would not like this behavior you can leave the field for the path to watch empty. 

The rationale is that when I created this app for myself macOS would save screenshots to the desktop by default and it was the easiest way to upload them instead of building my own thing. I didn't scope it to just screenshots because I found the workflow of dragging stuff to the desktop to upload not bad. Now that you can drag to the menu bar I may reconsider. 

At some point I probably will build my own screenshot tool if I can get the performance right.

**Comment by SamuelMereau** [comment]
Ah ok, thanks for the tip. Using bone I wasn't entirely certain whether this was a feature or not. I do see how it would benefit some workflows, however. Regardless it is a handy tool so I look forward to continue using it.
